apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "logging.base" . }}-fluentd-buffer
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.fluentdBuffer.size }}
