apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "logging.base" . }}-minio-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.minio.size }}
