apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logging.base" . }}-secrets
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.secrets.minioRootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minioRootPassword | quote }}
