apiVersion: v1
kind: Service
metadata:
  name: {{ include "l3.base" . }}-l3-app
spec:
  type: {{ .Values.global.serviceType }}
  selector:
    app: {{ include "l3.base" . }}-l3-app
  ports:
  - name: http
    port: {{ .Values.l3App.service.port }}
    targetPort: {{ .Values.l3App.service.port }}
