apiVersion: v1
kind: Service
metadata:
  name: {{ include "l3.base" . }}-openfga
spec:
  type: {{ .Values.global.serviceType }}
  selector:
    app: {{ include "l3.base" . }}-openfga
  ports:
  - name: api
    port: {{ .Values.openfga.service.apiPort }}
    targetPort: {{ .Values.openfga.service.apiPort }}
  - name: metrics
    port: {{ .Values.openfga.service.metricsPort }}
    targetPort: {{ .Values.openfga.service.metricsPort }}
  - name: playground
    port: {{ .Values.openfga.service.playgroundPort }}
    targetPort: {{ .Values.openfga.service.playgroundPort }}
