apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "l3.base" . }}-postgres-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.postgres.size }}
