apiVersion: v1
kind: Service
metadata:
  name: {{ include "l3.base" . }}-postgres-openfga
spec:
  type: ClusterIP
  selector:
    app: {{ include "l3.base" . }}-postgres-openfga
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
