apiVersion: v1
kind: Secret
metadata:
  name: {{ include "l3.base" . }}-secrets
type: Opaque
stringData:
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloakAdminPassword | quote }}
  KEYCLOAK_DB_PASSWORD: {{ .Values.secrets.keycloakDbPassword | quote }}
  OPENFGA_DB_PASSWORD: {{ .Values.secrets.openfgaDbPassword | quote }}
  L3_KEYCLOAK_INTROSPECT_CLIENT_SECRET: {{ .Values.secrets.l3KeycloakIntrospectClientSecret | quote }}
