apiVersion: v1
kind: Service
metadata:
  name: {{ include "l2.base" . }}-gateway
spec:
  type: {{ .Values.global.serviceType }}
  selector:
    app: {{ include "l2.base" . }}-gateway
  ports:
  - name: http
    port: {{ .Values.gateway.service.port }}
    targetPort: {{ .Values.gateway.service.port }}

