{{- $defaultKeycloakUrl := printf "http://%s-l3-keycloak:8082" .Release.Name -}}
{{- $gatewayKeycloakUrl := default $defaultKeycloakUrl .Values.gateway.keycloakUrl -}}
{{- $gatewayJwtIssuerUri := default (printf "%s/realms/%s" $gatewayKeycloakUrl .Values.gateway.realm) .Values.gateway.issuerUri -}}
{{- $gatewayJwtJwkSetUri := default (printf "%s/realms/%s/protocol/openid-connect/certs" $gatewayKeycloakUrl .Values.gateway.realm) .Values.gateway.jwkSetUri -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "l2.base" . }}-gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "l2.base" . }}-gateway
  template:
    metadata:
      labels:
        app: {{ include "l2.base" . }}-gateway
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.gateway.service.port }}
        env:
        - name: FGA_STORE_ID
          value: {{ .Values.gateway.fgaStoreId | quote }}
        - name: FGA_MODEL_ID
          value: {{ .Values.gateway.fgaModelId | quote }}
        - name: KEYCLOAK_URL
          value: {{ $gatewayKeycloakUrl | quote }}
        - name: KEYCLOAK_REALM
          value: {{ .Values.gateway.realm | quote }}
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          value: {{ $gatewayJwtIssuerUri | quote }}
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
          value: {{ $gatewayJwtJwkSetUri | quote }}
        - name: FGA_URL
          value: "http://{{ .Release.Name }}-l3-openfga:8083"
        - name: DB_URL
          value: "jdbc:postgresql://{{ .Release.Name }}-l3-postgres:5432/postgres"
        - name: DB_SCHEMA
          value: "public"
        - name: DB_USERNAME
          value: "keycloak"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "l2.secretName" . }}
              key: GATEWAY_DB_PASSWORD
        - name: VALID_API_KEYS
          value: "2dfd3409-ce01-4451-96fa-7e10c9681422y"
        - name: VALID_API_KEYS_ENABLED
          value: "true"
        - name: AUTHZEN_AUTHORIZATION_ENABLED
          value: "true"
        - name: LOGLEVEL
          value: "DEBUG"
