apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment.appName" . }}
spec:
  type: {{ default .Values.global.serviceType .Values.paymentApp.service.type }}
  selector:
    app: {{ include "payment.appName" . }}
  ports:
  - name: http
    port: {{ .Values.paymentApp.service.port }}
    targetPort: {{ .Values.paymentApp.service.targetPort }}


