{{- if .Values.paymentCheckL2Log.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment.checkL2LogSecretName" . }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.paymentCheckL2Log.secrets.postgresPassword | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.paymentCheckL2Log.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.paymentCheckL2Log.secrets.awsSecretAccessKey | quote }}
{{- end }}
