apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "payment.base" . }}-db-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.paymentDb.size }}


