apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment.secretName" . }}
type: Opaque
stringData:
  PAYMENT_SECRET_KEY: {{ .Values.secrets.paymentSecretKey | quote }}
  PAYMENT_API_KEY: {{ .Values.secrets.paymentApiKey | quote }}
  PAYMENT_L3_CLIENT_SECRET: {{ .Values.secrets.paymentL3ClientSecret | quote }}
