apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mockoon.service.name }}
spec:
  type: {{ .Values.global.serviceType }}
  selector:
    app: {{ include "mockserver.base" . }}-mockoon
  ports:
  - name: http
    port: {{ .Values.mockoon.service.port }}
    targetPort: {{ .Values.mockoon.service.port }}
