# =========================
# SOURCE: Kubernetes gateway container logs (tail)
# =========================
<source>
  @type tail
  @id gateway_tail_input
  path /var/log/containers/*l2-gateway*.log
  pos_file /tmp/fluentd-buf/gateway.pos
  tag kubernetes.gateway
  read_from_head true
  <parse>
    @type regexp
    expression /^(?<time>[^ ]+) (?<stream>stdout|stderr) [^ ] (?<log>.*)$/
    time_key time
    time_type string
    keep_time_key true
  </parse>
</source>

# =========================
# FILTER: message/log が空でないものだけ通す,log キーを抽出
# =========================
<filter **>
  @type grep
  <regexp>
    key log
    pattern .+
  </regexp>
</filter>

# 末尾の改行
# <filter **>
#   @type record_transformer
#   enable_ruby true
#   <record>
#     log <trimmed message>
#   </record>
# </filter>

# =========================
# MATCH: MinIO(S3互換)へ出力
# =========================
<match **>
  @type s3

  aws_key_id     minio-sample #minio-pj-a-sbx
  aws_sec_key    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX # SN7mbLGN7snFcAqH69egDnCa

  s3_bucket      pj-a-sbx
  s3_endpoint    http://minio:9000
  force_path_style true

  path           applogs/
  time_slice_format %Y%m%d-%H

  store_as gzip
  s3_object_key_format %{path}%{time_slice}_%{index}.%{file_extension}

  <format>
    @type json
  </format>

  <buffer time>
    @type file
    path /tmp/fluentd-buf/minio

    timekey 3600
    timekey_use_utc false
    timekey_wait 300s

    flush_interval 10s
    flush_at_shutdown true
  </buffer>
</match>
